version: "3.8"


services:
  fastapi:
    image: web
    build:
      context: .
      dockerfile: src/Dockerfile
    ports:
      - "8005:8005"
    volumes:
      - ./src:/src
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8005